# Generated by Django 5.0.14 on 2026-08-16 00:22

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="NosotrosPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "noindex",
                    models.BooleanField(
                        default=False,
                        help_text="Marca esta casilla para pedir a los buscadores que no muestren esta página en resultados.",
                        verbose_name="No indexar en buscadores",
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True, verbose_name="Introducción")),
                ("mision", wagtail.fields.RichTextField(verbose_name="Misión")),
                ("vision", wagtail.fields.RichTextField(verbose_name="Visión")),
                (
                    "imagen_social",
                    models.ForeignKey(
                        blank=True,
                        help_text="Se usa como imagen Open Graph / Twitter Card al compartir esta página. Si se deja vacía, Fase 5 definirá una imagen por defecto.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Imagen para redes sociales",
                    ),
                ),
            ],
            options={
                "verbose_name": "Página de nosotros",
            },
            bases=("wagtailcore.page", models.Model),
        ),
        migrations.CreateModel(
            name="MiembroEquipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                ("nombre", models.CharField(max_length=150, verbose_name="Nombre")),
                ("cargo", models.CharField(max_length=150, verbose_name="Cargo")),
                ("bio", models.TextField(blank=True, verbose_name="Biografía breve")),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Desactívalo para ocultarlo del equipo sin borrar sus datos.",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "foto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Foto",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipo",
                        to="nosotros.nosotrospage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Integrante del equipo",
                "verbose_name_plural": "Equipo",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HitoLineaTiempo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                (
                    "anio",
                    models.CharField(
                        help_text="Ej. '2015' o un rango como '2015-2018'.",
                        max_length=20,
                        verbose_name="Año",
                    ),
                ),
                ("titulo", models.CharField(max_length=150, verbose_name="Título")),
                ("descripcion", models.TextField(blank=True, verbose_name="Descripción")),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hitos_historia",
                        to="nosotros.nosotrospage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hito de la historia",
                "verbose_name_plural": "Historia (línea de tiempo)",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Valor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                ("nombre", models.CharField(max_length=80, verbose_name="Nombre")),
                (
                    "icono",
                    models.CharField(
                        help_text="Nombre clave del icono, ej. 'corazon', 'manos'. El catálogo visual se define en Fase 2.",
                        max_length=50,
                        verbose_name="Icono",
                    ),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valores",
                        to="nosotros.nosotrospage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valor",
                "verbose_name_plural": "Valores",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
