# Generated by Django 5.0.14 on 2026-08-16 00:22

import django.core.validators
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="imagen_social",
            field=models.ForeignKey(
                blank=True,
                help_text="Se usa como imagen Open Graph / Twitter Card al compartir esta página. Si se deja vacía, Fase 5 definirá una imagen por defecto.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Imagen para redes sociales",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="noindex",
            field=models.BooleanField(
                default=False,
                help_text="Marca esta casilla para pedir a los buscadores que no muestren esta página en resultados.",
                verbose_name="No indexar en buscadores",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="secciones",
            field=wagtail.fields.StreamField(
                [
                    ("cifras_impacto", 1),
                    ("conocenos", 1),
                    ("areas_de_trabajo", 1),
                    ("proyectos", 3),
                    ("testimonios", 5),
                    ("como_ayudar", 1),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Déjalo vacío para usar el título por defecto.",
                            "label": "Título de la sección",
                            "required": False,
                        },
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("titulo", 0)]], {}),
                    2: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 3,
                            "label": "Cantidad de proyectos a mostrar",
                            "max_value": 12,
                            "min_value": 1,
                        },
                    ),
                    3: ("wagtail.blocks.StructBlock", [[("titulo", 0), ("cantidad", 2)]], {}),
                    4: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 3,
                            "label": "Cantidad de testimonios a mostrar",
                            "max_value": 12,
                            "min_value": 1,
                        },
                    ),
                    5: ("wagtail.blocks.StructBlock", [[("titulo", 0), ("cantidad", 4)]], {}),
                },
                help_text="Agrega y ordena las secciones de la portada, sin repetirlas.",
                verbose_name="Orden de secciones",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="subtitulo",
            field=models.CharField(blank=True, max_length=300, verbose_name="Subtítulo"),
        ),
        migrations.AddField(
            model_name="homepage",
            name="titular",
            field=models.CharField(default="", max_length=200, verbose_name="Titular"),
        ),
        migrations.AddField(
            model_name="homepage",
            name="video_fondo",
            field=models.FileField(
                blank=True,
                help_text="MP4 o WebM, recomendado menos de 2MB, 8-12 segundos, sin audio. Alternativa: completa la URL de video más abajo.",
                upload_to="home/videos/",
                validators=[django.core.validators.FileExtensionValidator(["mp4", "webm"])],
                verbose_name="Video de fondo (archivo)",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="video_fondo_movil",
            field=models.FileField(
                blank=True,
                help_text="Opcional. Versión más liviana del video para conexiones móviles.",
                upload_to="home/videos/",
                validators=[django.core.validators.FileExtensionValidator(["mp4", "webm"])],
                verbose_name="Video de fondo para móvil (opcional)",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="video_fondo_poster",
            field=models.ForeignKey(
                help_text="Obligatoria. Se muestra mientras el video carga, en móvil y cuando la persona prefiere movimiento reducido.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Imagen de portada del video (poster)",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="video_fondo_url",
            field=models.URLField(
                blank=True,
                help_text="Alternativa a subir un archivo: enlace a un video alojado externamente. Si ambos campos están completos, el archivo subido tiene prioridad.",
                verbose_name="Video de fondo (URL)",
            ),
        ),
        migrations.CreateModel(
            name="BotonHero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                ("texto", models.CharField(max_length=50, verbose_name="Texto del botón")),
                ("url_externa", models.URLField(blank=True, verbose_name="URL externa")),
                (
                    "estilo",
                    models.CharField(
                        choices=[("primario", "Primario"), ("secundario", "Secundario")],
                        default="primario",
                        max_length=20,
                        verbose_name="Estilo",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="botones_hero",
                        to="home.homepage",
                    ),
                ),
                (
                    "pagina_destino",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                        verbose_name="Página de destino",
                    ),
                ),
            ],
            options={
                "verbose_name": "Botón del hero",
                "verbose_name_plural": "Botones del hero",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CifraImpacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                ("numero", models.PositiveIntegerField(verbose_name="Número")),
                (
                    "sufijo",
                    models.CharField(
                        blank=True,
                        help_text="Ej. '+', '%', 'k'.",
                        max_length=10,
                        verbose_name="Sufijo",
                    ),
                ),
                ("etiqueta", models.CharField(max_length=100, verbose_name="Etiqueta")),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cifras_impacto",
                        to="home.homepage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cifra de impacto",
                "verbose_name_plural": "Cifras de impacto",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
