# Generated by Django 5.0.14 on 2026-08-16 00:22

import django.core.validators
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaDeTrabajoPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "noindex",
                    models.BooleanField(
                        default=False,
                        help_text="Marca esta casilla para pedir a los buscadores que no muestren esta página en resultados.",
                        verbose_name="No indexar en buscadores",
                    ),
                ),
                (
                    "icono_svg",
                    models.FileField(
                        help_text="Archivo SVG. Se muestra siempre como imagen, nunca insertado directo en el HTML.",
                        upload_to="areas/iconos/",
                        validators=[django.core.validators.FileExtensionValidator(["svg"])],
                        verbose_name="Ícono (SVG)",
                    ),
                ),
                (
                    "descripcion_corta",
                    models.CharField(
                        help_text="Resumen breve para tarjetas y menús.",
                        max_length=200,
                        verbose_name="Descripción corta",
                    ),
                ),
                (
                    "descripcion_larga",
                    wagtail.fields.RichTextField(verbose_name="Descripción larga"),
                ),
                (
                    "color_acento",
                    models.CharField(
                        help_text="Color hexadecimal, ej. #12369B.",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9A-Fa-f]{6}$",
                                "Ingresa un color hexadecimal válido, ej. #12369B.",
                            )
                        ],
                        verbose_name="Color de acento",
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Si está desactivada, el área no aparece en los listados aunque la página siga publicada.",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "imagen",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Imagen",
                    ),
                ),
                (
                    "imagen_social",
                    models.ForeignKey(
                        blank=True,
                        help_text="Se usa como imagen Open Graph / Twitter Card al compartir esta página. Si se deja vacía, Fase 5 definirá una imagen por defecto.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Imagen para redes sociales",
                    ),
                ),
            ],
            options={
                "verbose_name": "Área de trabajo",
                "verbose_name_plural": "Áreas de trabajo",
            },
            bases=("wagtailcore.page", models.Model),
        ),
        migrations.CreateModel(
            name="AreasIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "noindex",
                    models.BooleanField(
                        default=False,
                        help_text="Marca esta casilla para pedir a los buscadores que no muestren esta página en resultados.",
                        verbose_name="No indexar en buscadores",
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Texto introductorio antes del listado de áreas.",
                        verbose_name="Introducción",
                    ),
                ),
                (
                    "imagen_social",
                    models.ForeignKey(
                        blank=True,
                        help_text="Se usa como imagen Open Graph / Twitter Card al compartir esta página. Si se deja vacía, Fase 5 definirá una imagen por defecto.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Imagen para redes sociales",
                    ),
                ),
            ],
            options={
                "verbose_name": "Índice de áreas de trabajo",
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
