# Generated by Django 5.0.14 on 2026-08-16 00:22

import django.core.validators
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("areas", "0001_initial"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("voluntario", "Quiero ser voluntario/a"),
                            ("donacion", "Quiero donar"),
                            ("empresa", "Colaborar como empresa"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                ("apellido", models.CharField(max_length=100, verbose_name="Apellido")),
                ("email", models.EmailField(max_length=254, verbose_name="Correo electrónico")),
                (
                    "telefono",
                    models.CharField(
                        help_text="Con prefijo de país. Ej. +51 999 999 999.",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+?\\d{1,3}[\\s-]?\\d{6,12}$",
                                "Ingresa un teléfono válido, con prefijo de país. Ej. +51 999 999 999.",
                            )
                        ],
                        verbose_name="Teléfono",
                    ),
                ),
                ("mensaje", models.TextField(verbose_name="Mensaje")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("nuevo", "Nuevo"),
                            ("en_proceso", "En proceso"),
                            ("atendido", "Atendido"),
                            ("descartado", "Descartado"),
                        ],
                        default="nuevo",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP de origen"
                    ),
                ),
                (
                    "origen",
                    models.CharField(
                        blank=True,
                        help_text="Página o formulario de origen.",
                        max_length=100,
                        verbose_name="Origen",
                    ),
                ),
                (
                    "disponibilidad",
                    models.CharField(blank=True, max_length=150, verbose_name="Disponibilidad"),
                ),
                (
                    "profesion",
                    models.CharField(blank=True, max_length=100, verbose_name="Profesión"),
                ),
                ("ciudad", models.CharField(blank=True, max_length=100, verbose_name="Ciudad")),
                (
                    "tipo_donacion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("monetaria", "Monetaria"),
                            ("especie", "En especie"),
                            ("recurrente", "Recurrente"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de donación",
                    ),
                ),
                (
                    "rango_aporte",
                    models.CharField(
                        blank=True,
                        help_text="Texto libre, ej. 'S/ 50 - S/ 100 mensual'.",
                        max_length=100,
                        verbose_name="Rango de aporte",
                    ),
                ),
                (
                    "desea_recibo",
                    models.BooleanField(default=False, verbose_name="Desea recibo por donación"),
                ),
                (
                    "razon_social",
                    models.CharField(blank=True, max_length=200, verbose_name="Razón social"),
                ),
                (
                    "ruc",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{11}$", "El RUC debe tener 11 dígitos numéricos."
                            )
                        ],
                        verbose_name="RUC",
                    ),
                ),
                ("cargo", models.CharField(blank=True, max_length=100, verbose_name="Cargo")),
                (
                    "tipo_alianza",
                    models.CharField(blank=True, max_length=150, verbose_name="Tipo de alianza"),
                ),
                (
                    "areas_interes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="voluntarios_interesados",
                        to="areas.areadetrabajopage",
                        verbose_name="Áreas de interés",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contacto",
                "verbose_name_plural": "Contactos",
                "ordering": ["-creado"],
            },
        ),
        migrations.CreateModel(
            name="ContactoPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "noindex",
                    models.BooleanField(
                        default=False,
                        help_text="Marca esta casilla para pedir a los buscadores que no muestren esta página en resultados.",
                        verbose_name="No indexar en buscadores",
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Texto antes de los tres formularios.",
                        verbose_name="Introducción",
                    ),
                ),
                (
                    "imagen_social",
                    models.ForeignKey(
                        blank=True,
                        help_text="Se usa como imagen Open Graph / Twitter Card al compartir esta página. Si se deja vacía, Fase 5 definirá una imagen por defecto.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Imagen para redes sociales",
                    ),
                ),
            ],
            options={
                "verbose_name": "Página de contacto",
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
