# Generated by Django 5.0.14 on 2026-08-16 00:15

import django.core.validators
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "nombre_legal",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nombre legal de la organización"
                    ),
                ),
                (
                    "ruc",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{11}$", "El RUC debe tener 11 dígitos numéricos."
                            )
                        ],
                        verbose_name="RUC",
                    ),
                ),
                ("direccion", models.TextField(blank=True, verbose_name="Dirección")),
                (
                    "texto_legal_footer",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Ej. datos de inscripción como asociación sin fines de lucro.",
                        verbose_name="Texto legal del pie de página",
                    ),
                ),
                (
                    "correo_general",
                    models.EmailField(blank=True, max_length=254, verbose_name="Correo general"),
                ),
                (
                    "correo_voluntariado",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Correo de voluntariado"
                    ),
                ),
                (
                    "correo_donaciones",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Correo de donaciones"
                    ),
                ),
                (
                    "correo_empresas",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Correo para empresas"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True,
                        help_text="Con prefijo de país. Ej. +51 999 999 999.",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+?\\d{1,3}[\\s-]?\\d{6,12}$",
                                "Ingresa un teléfono válido, con prefijo de país. Ej. +51 999 999 999.",
                            )
                        ],
                        verbose_name="Teléfono",
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True,
                        help_text="Con prefijo de país. Ej. +51 999 999 999.",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+?\\d{1,3}[\\s-]?\\d{6,12}$",
                                "Ingresa un teléfono válido, con prefijo de país. Ej. +51 999 999 999.",
                            )
                        ],
                        verbose_name="WhatsApp",
                    ),
                ),
                (
                    "google_analytics_id",
                    models.CharField(
                        blank=True,
                        help_text="Formato G-XXXXXXX.",
                        max_length=50,
                        verbose_name="ID de Google Analytics",
                    ),
                ),
                (
                    "meta_pixel_id",
                    models.CharField(blank=True, max_length=50, verbose_name="ID de Meta Pixel"),
                ),
                (
                    "favicon",
                    models.ForeignKey(
                        blank=True,
                        help_text="Idealmente una imagen cuadrada simple, se usa en la pestaña del navegador.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Favicon",
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración del sitio",
            },
        ),
        migrations.CreateModel(
            name="RedSocial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                (
                    "red",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("tiktok", "TikTok"),
                            ("youtube", "YouTube"),
                            ("linkedin", "LinkedIn"),
                            ("x", "X (Twitter)"),
                            ("whatsapp", "WhatsApp"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Red social",
                    ),
                ),
                ("url", models.URLField(verbose_name="URL")),
                (
                    "settings",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redes_sociales",
                        to="core.sitesettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Red social",
                "verbose_name_plural": "Redes sociales",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
