# Generated by Django 5.0.14 on 2026-08-16 00:22

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("areas", "0001_initial"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProyectoPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "noindex",
                    models.BooleanField(
                        default=False,
                        help_text="Marca esta casilla para pedir a los buscadores que no muestren esta página en resultados.",
                        verbose_name="No indexar en buscadores",
                    ),
                ),
                ("resumen", models.CharField(max_length=300, verbose_name="Resumen")),
                (
                    "contenido",
                    wagtail.fields.StreamField(
                        [
                            ("parrafo", 0),
                            ("imagen", 3),
                            ("cita", 7),
                            ("galeria", 9),
                            ("video", 10),
                            ("datos", 16),
                        ],
                        blank=True,
                        block_lookup={
                            0: ("core.blocks.ParrafoBlock", (), {}),
                            1: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Imagen"}),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Leyenda", "required": False},
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("imagen", 1), ("leyenda", 2)]],
                                {},
                            ),
                            4: ("wagtail.blocks.TextBlock", (), {"label": "Cita"}),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Autor", "required": False},
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Ej. 'Voluntaria, Proyecto Aulas Abiertas'.",
                                    "label": "Rol o relación",
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [[("texto", 4), ("autor", 5), ("rol", 6)]],
                                {},
                            ),
                            8: ("wagtail.blocks.ListBlock", (1,), {"label": "Imágenes"}),
                            9: ("wagtail.blocks.StructBlock", [[("imagenes", 8)]], {}),
                            10: ("core.blocks.VideoBlock", (), {}),
                            11: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Título", "required": False},
                            ),
                            12: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Ej. '120', '+300', '85%'.", "label": "Número"},
                            ),
                            13: ("wagtail.blocks.CharBlock", (), {"label": "Etiqueta"}),
                            14: (
                                "wagtail.blocks.StructBlock",
                                [[("numero", 12), ("etiqueta", 13)]],
                                {},
                            ),
                            15: ("wagtail.blocks.ListBlock", (14,), {"label": "Datos"}),
                            16: (
                                "wagtail.blocks.StructBlock",
                                [[("titulo", 11), ("datos", 15)]],
                                {},
                            ),
                        },
                        verbose_name="Contenido",
                    ),
                ),
                (
                    "ubicacion",
                    models.CharField(
                        help_text="Distrito/ciudad y región, ej. 'Villa El Salvador, Lima'.",
                        max_length=150,
                        verbose_name="Ubicación",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(blank=True, null=True, verbose_name="Fecha de inicio"),
                ),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True,
                        help_text="Déjalo vacío si el proyecto sigue en curso.",
                        null=True,
                        verbose_name="Fecha de fin",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("planificado", "Planificado"),
                            ("en_curso", "En curso"),
                            ("finalizado", "Finalizado"),
                        ],
                        default="planificado",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "beneficiarios",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Número de beneficiarios"
                    ),
                ),
                (
                    "destacado",
                    models.BooleanField(
                        default=False,
                        help_text="Los proyectos destacados aparecen primero en la portada.",
                        verbose_name="Destacado",
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proyectos",
                        to="areas.areadetrabajopage",
                        verbose_name="Área de trabajo",
                    ),
                ),
                (
                    "imagen_destacada",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Imagen destacada",
                    ),
                ),
                (
                    "imagen_social",
                    models.ForeignKey(
                        blank=True,
                        help_text="Se usa como imagen Open Graph / Twitter Card al compartir esta página. Si se deja vacía, Fase 5 definirá una imagen por defecto.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Imagen para redes sociales",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proyecto",
            },
            bases=("wagtailcore.page", models.Model),
        ),
        migrations.CreateModel(
            name="ImagenGaleria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                ("leyenda", models.CharField(blank=True, max_length=200, verbose_name="Leyenda")),
                (
                    "imagen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Imagen",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="galeria",
                        to="proyectos.proyectopage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foto de galería",
                "verbose_name_plural": "Galería de fotos",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Aliado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                ("nombre", models.CharField(max_length=150, verbose_name="Nombre")),
                ("url", models.URLField(blank=True, verbose_name="URL")),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliados",
                        to="proyectos.proyectopage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aliado",
                "verbose_name_plural": "Aliados",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProyectosIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "noindex",
                    models.BooleanField(
                        default=False,
                        help_text="Marca esta casilla para pedir a los buscadores que no muestren esta página en resultados.",
                        verbose_name="No indexar en buscadores",
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True, verbose_name="Introducción")),
                (
                    "imagen_social",
                    models.ForeignKey(
                        blank=True,
                        help_text="Se usa como imagen Open Graph / Twitter Card al compartir esta página. Si se deja vacía, Fase 5 definirá una imagen por defecto.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Imagen para redes sociales",
                    ),
                ),
            ],
            options={
                "verbose_name": "Índice de proyectos",
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
