# Generated by Django 5.0.14 on 2026-08-16 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("proyectos", "0001_initial"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(max_length=150, verbose_name="Nombre")),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("voluntario", "Voluntario/a"),
                            ("beneficiario", "Beneficiario/a"),
                            ("aliado", "Aliado/a"),
                        ],
                        max_length=20,
                        verbose_name="Rol",
                    ),
                ),
                ("texto", models.TextField(verbose_name="Testimonio")),
                ("orden", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Desactívalo para ocultarlo del sitio sin borrarlo.",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "foto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Foto",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="testimonios",
                        to="proyectos.proyectopage",
                        verbose_name="Proyecto relacionado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Testimonio",
                "verbose_name_plural": "Testimonios",
                "ordering": ["orden"],
            },
        ),
    ]
